ci: version to 4.0.0 Micronaut 4.0.0-SNAPSHOT githubCoreBranch=4.0.x
micronaut-projects/micronaut-kotlin pull request #422
Opened 2022-08-16 18:52 UTC by wetted

closes #395 
closes #399 
closes #398 
closes #403 

satisfies task in https://github.com/micronaut-projects/micronaut-core/issues/7720

this breaks the test `QualifiersExtensionsTest.qualifierByAnnotation()` but I'm not yet sure why

2022-09-07 18:12 UTC, sdelamo requested changes
Why does it fail?

2022-09-07 18:12 UTC, sdelamo commented on gradle.properties
> +micronautTestVersion=3.4.0
this should be 3.5.0

2022-09-07 19:06 UTC, wetted commented
> Why does it fail?

@sdelamo This has several issues I need to address for the kotlin/ktor upgrades. It's a WIP.

2022-09-08 15:09 UTC, wetted commented
#403 and #413 to upgrade ktor are a bit more involved with breaking changes to dependency coordinates, package names and API. I will work this on a separate PR.

2022-09-13 11:12 UTC, sdelamo approved these changes

2022-09-13 11:12 UTC, merged